### PR TITLE
snmp-subagent changes for bookworm upgrade

### PR DESCRIPTION
**Pull request by mohan-selvaraj**
**- What I did**
remove loop argument from asyncio APIs

**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Comment by mohan-selvaraj** [comment]
To be combined with "bookworm container upgrade for lldp, net-snmp" PR
https://github.com/sonic-net/sonic-buildimage/pull/18150

**Comment by saiarcot895** [comment]
@qiluo-msft, could you help to review this, or assign someone to review? Some additional context: https://stackoverflow.com/a/60315290

**Review by saiarcot895 — APPROVED** [review]

**Comment by adyeung** [comment]
@qiluo-msft @SuvarnaMeenakshi pls review this is blocking lldp bookworm migration

**Comment by saiarcot895** [comment]
Could you include https://github.com/sonic-net/sonic-snmpagent/pull/315/commits/2dbbb5c92a25f9f4e2aa488f21e7259516dd2df5 in your branch? This is to add some code coverage for these changes. This will bump up the code coverage to 83%

**Comment by mohan-selvaraj** [comment]
> Could you include [2dbbb5c](https://github.com/sonic-net/sonic-snmpagent/commit/2dbbb5c92a25f9f4e2aa488f21e7259516dd2df5) in your branch? This is to add some code coverage for these changes. This will bump up the code coverage to 83%

Couldn't directly pull the commit. Added the changes to the branch and mentioned the commit ID in the commit message. 
Thank you.

**Review by qiluo-msft — APPROVED** [review]

**Pull request merged**
